import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import StoreProvider from "./redux";
import DashboardWrapper from "./dashboardWrapper";

const inter = Inter({ subsets: ["greek"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
  icons:{
    icon:"next.svg"
  }
};

export default function RootLayout({
  children,
  
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <DashboardWrapper>
              {children}
          </DashboardWrapper>  
        </StoreProvider>
      </body>
    </html>
  );
}
